language: java

# whitelist
branches:
  only:
   - master

jdk:
   - oraclejdk8

notifications:
  email:
    recipients:
     - my.gama.bot@gmail.com

cache:
  directories:
    - $HOME/.m2

script: sh ./build.sh
