sudo: required
language: java
jdk:
  - oraclejdk8
before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
  - echo "MAVEN_OPTS='-Dorg.slf4j.simpleLogger.defaultLogLevel=error -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xmx2048m'" >> ~/.mavenrc
notifications:
  email:
    recipients:
      - my.gama.bot@gmail.com
    on_success: change
    on_failure: always
cache:
  directories:
    - "$HOME/.m2"
addons:
    apt:
        packages:      
            - sshpass
            - oracle-java8-installer
    ssh_known_hosts:
      - 51.255.46.42
    # https://docs.travis-ci.com/user/sonarcloud/#inspecting-code-with-the-sonarqube-scanner
    sonarcloud:
      organization: "gama-platform" # the key of the org you chose at step #3
      token:
        secure: "$SONAR_TOKEN"
script: 
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=gama-platform_gama
  - bash ./travis/compile.sh	
  - bash ./travis/validate_and_test.sh
after_success:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - export SSHPASS=$USER_PWD 
  - bash ./travis/publish.sh
branches:
  only:
    - master
