language: java

install:
  - git config --global user.email "my.gama.bot@gmail.com"
  - git config --global user.name "gama-bot"

# whitelist
branches:
  only:
   - mavencasse

jdk:
   - oraclejdk8
   - openjdk7

notifications:
  email: 
    on_success: always
    on_failure: always
  recipients:
    - gama-dev@googlegroups.com
