language: java
jdk:
  - oraclejdk8
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
notifications:
  email:
    recipients:
    - my.gama.bot@gmail.com
    on_success: change
    on_failure: always
cache:
  directories:
  - "$HOME/.m2"
script: 
- export MAVEN_OPTS='-Xmx512m -XX:MaxPermSize=128m'
- sh ./build.sh
after_success: bash ./github-release.sh "$TRAVIS_COMMIT" 
branches:
  only:
    - master
